// <auto-generated />
using Fishward.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fishward.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021212800_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fishward.Data.Models.Player", b =>
                {
                    b.Property<decimal>("DiscordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("DiscordID");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Fishward.Data.Models.PlayerResources", b =>
                {
                    b.Property<decimal>("DiscordID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.HasKey("DiscordID");

                    b.ToTable("player_resources", (string)null);
                });

            modelBuilder.Entity("Fishward.Data.Models.PlayerResources", b =>
                {
                    b.HasOne("Fishward.Data.Models.Player", "Player")
                        .WithOne("PlayerResource")
                        .HasForeignKey("Fishward.Data.Models.PlayerResources", "DiscordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Fishward.Data.Models.Player", b =>
                {
                    b.Navigation("PlayerResource")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
